[Service]
ExecStart=
ExecStart=/opt/dell-broadcom-fingerprint-helper/bin/fprintd
Environment=LD_LIBRARY_PATH=/opt/dell-broadcom-fingerprint-helper/lib
Environment=FP_TOD_DRIVERS_DIR=/opt/dell-broadcom-fingerprint-helper/lib/libfprint-2/tod-1
